server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
redis:
    host: 127.0.0.1
    port: 6379
